<a href="https://colab.research.google.com/github/thesrinivasprabhu/selfstudyml/blob/main/linearregin2variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [18]:
ds = pd.read_csv("linreg2var.csv")
ds

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [19]:
a = ds.bedrooms.median()
print(a)
import math as m
a = m.floor(a)
a

3.5


3

In [20]:
ds.bedrooms.fillna(a)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [21]:
ds


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [22]:
ds.bedrooms = ds.bedrooms.fillna(a)
ds

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [24]:
reg = linear_model.LinearRegression()
reg.fit(ds[["area","bedrooms","age"]],ds.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
a1 , a2 , a3 = reg.coef_
a

array([   137.25, -26025.  ,  -6825.  ])

In [30]:
b = reg.intercept_
b

383724.99999999994

In [32]:
reg.predict([[3000,3,40]])

array([444400.])

In [35]:
predval = a1*3000 + a2*3 + a3*40 +b
predval

444400.00000000006

Saving the model....

In [36]:
import pickle

In [39]:
with open('mymodel','wb')as f:
    pickle.dump(reg,f)

In [40]:
with open('mymodel','rb')as g:
   l =  pickle.load(g)

In [41]:
l.predict([[3000,3,40]])

array([444400.])

In [47]:
from sklearn.externals import joblib as p
with open('mymodelsk','wb')as f:
    p.dump(reg,f)

In [48]:
with open('mymodelsk','rb')as g:
   l =  p.load(g)

In [49]:
l.predict([[3000,3,40]])

array([444400.])